version: "3"

services:

  app:
    build: ./app
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    env_file:
      - ./docker/pg-variables.env

  postgres:
    image: postgres:14.4
    restart: always
    env_file:
      - ./docker/pg-variables.env